import './globals.scss';
import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: {
    default: 'Home page | UpLeveled',
    template: '%s | UpLeveled',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>
            {/* <CookieBanner /> */}
            <nav>
              {/* <a href="/">
                <img src="./images/logo.png" alt="Logo" className="logo" /> Home
              </a> */}
              <Link href="/">Home</Link>
              <Link href="/retreats">Retreats</Link>
              <Link href="/about">About</Link>
              <Link href="/contact">Contact</Link>
            </nav>
          </div>
        </header>
        <main>{children}</main>

        <footer>Hello Footer</footer>
      </body>
    </html>
  );
}
